name: CI/CD Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - maser

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'  # Adjust based on your requirements

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm run test -- --watch=false

      - name: Build project
        run: npm run build -- --prod

      - name: Deploy to Server (Optional)
        run: |
          echo "Deploying to server..."
          # Add your deployment commands here, for example:
          # npm install -g firebase-tools
          # firebase deploy --only hosting
